-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Employers"
(
    "UserId" integer NOT NULL,
    "CompanyName" character varying(250),
    "WebSiteName" character varying(250),
    "PhoneNumber" character varying(20),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."JobPositions"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EmployerUserId" integer,
    "Description" character varying(250),
    PRIMARY KEY ("Id")
);

CREATE TABLE public."JobSeekers"
(
    "UserId" integer NOT NULL,
    "FirstName" character varying(75),
    "LastName" character varying(75),
    "NationalityId" character(11),
    "BirthDate" date,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."SystemStaffs"
(
    "UserId" integer NOT NULL,
    "FirstName" character varying(75),
    "LastName" character varying(75),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Users"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EMail" character varying(100),
    "Password" character varying(15),
    PRIMARY KEY ("Id")
);

ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."JobPositions"
    ADD FOREIGN KEY ("EmployerUserId")
    REFERENCES public."Employers" ("UserId")
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."SystemStaffs"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;

END;